# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: 'Build'
#- task: SonarCloudPrepare@1
#  inputs:
#    SonarCloud: 'sonarcloud'
#    organization: 'julioazocar-1'
#    projectKey: 'project-microservicio-spring'
#    projectName: 'project-microservicio-spring'
#  displayName: 'SonarCloud prepare'
- task: SonarCloudPrepare@1
  displayName: Preparing sonar cloud project 
  inputs:
         SonarCloud: 'sonarcloud'
         organization: 'julioazocar-1'
         scannerMode: 'Other'
         extraProperties: |
           # Additional properties that will be passed to the scanner,
           # Put one key=value per line, example:
           # sonar.exclusions=**/*.bin
           sonar.projectKey=project-microservicio-spring
           sonar.projectName=project-microservicio-spring
#- task: Gradle@3
#  inputs:
#    gradleWrapperFile: 'gradlew'
#    tasks: 'sonar'
#    publishJUnitResults: false
#    javaHomeOption: 'JDKVersion'
#    sonarQubeRunAnalysis: true
#    sqGradlePluginVersionChoice: 'specify'
#    sonarQubeGradlePluginVersion: '3.5.0.2730'
#    spotBugsAnalysis: false

- task: Maven@3
  inputs:
         mavenPomFile: 'pom.xml'
         mavenOptions: '-Xmx3072m'
         javaHomeOption: 'JDKVersion'
         jdkVersionOption: '1.8'
         jdkArchitectureOption: 'x64'
         publishJUnitResults: true
         testResultsFiles: '**/surefire-reports/TEST-*.xml'
         mavenAuthenticateFeed: true
         goals: 'package'
         options: '-X -P azure_artifacts $(MAVEN_OPTS)' 
         sonarQubeRunAnalysis: true 
         sqMavenPluginVersionChoice: 'latest' # Required when sonarQubeRunAnalysis == True# Options: latest, pom         
    
- task: SonarCloudPublish@1
  displayName: publish analisys
  inputs:
      pollingTimeoutSec: '300'
- task: CopyFiles@1
  displayName: 'Coppy jar to pipeline artifact'
  inputs:
         SourceFolder: '$(System.DefaultWorkingDirectory)/target/'
         Contents: '*.jar'
         TargetFolder: '$(build.artifactstagingdirectory)/$(buildConfiguration)'
         CleanTargetFolder: true

#- script: |
 #   echo 'Ruta del archivo JAR:'
  #  echo '$(System.DefaultWorkingDirectory)/build/libs/microservicio-spring-1.0.0.jar'
  #displayName: 'Imprimir Ruta del Archivo JAR'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'julinf/microservicio-spring'
    command: 'build'
    Dockerfile: '**/Dockerfile'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'julinf/microservicio-spring'
    command: 'push'
- script: |
        echo Hola Mundo
  displayName: 'Hola Mundo'