
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarCloudPrepare@1
  inputs:
      SonarCloud: 'sonarcloud' # Nombre de la conexión a SonarCloud en Azure DevOps
      organization: 'julioazocar-1'
      scannerMode: 'CLI'
      configMode: 'manual'
      projectKey: 'project-microservicio-spring'
      projectName: 'project-microservicio-spring'
      cliSources: 'src'
      extraProperties: |
        sonar.java.source=1.8
        # Otras propiedades adicionales de análisis de SonarQube, si es necesario


- task: JavaToolInstaller@0
  inputs:
      versionSpec: '8'
      jdkArchitectureOption: 'x64'

- task: SonarCloudAnalyze@1

- task: Gradle@3
  inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'

- task: SonarCloudPublish@1
  inputs:
      pollingTimeoutSec: '300'

#- task: SonarCloudQualityGate@1  String does not match the pattern of "^PowerShell@2$".

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'julinf/microservicio-spring'
    command: 'build'
    Dockerfile: '**/Dockerfile'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'julinf/microservicio-spring'
    command: 'push'
- script: |
        echo Hola Mundo
  displayName: 'Hola Mundo'
