trigger:
- main

pool:
  vmImage: ubuntu-latest

steps: 

- task: SonarCloudPrepare@1
  displayName: Preparing sonar cloud project 
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'julioazocar-1'
    scannerMode: 'Other'
    extraProperties: |
     sonar.projectKey=project-microservicio-spring
     sonar.projectName=project-microservicio-spring

