
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarCloudPrepare@1
  displayName: Preparing sonar cloud project 
  inputs:
         SonarCloud: 'sonarcloud'
         organization: 'julioazocar-1'
         scannerMode: 'Other'
         extraProperties: |
           # Additional properties that will be passed to the scanner,
           # Put one key=value per line, example:
           # sonar.exclusions=**/*.bin
           sonar.projectKey=project-microservicio-spring
           sonar.projectName=project-microservicio-spring

- task: SonarCloudAnalyze@1

- task: Gradle@3
  inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'

- task: SonarCloudPublish@1
  inputs:
      pollingTimeoutSec: '300'

- task: SonarCloudQualityGate@1
  displayName: Check SonarCloud quality gate

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'julinf/microservicio-spring'
    command: 'build'
    Dockerfile: '**/Dockerfile'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'julinf/microservicio-spring'
    command: 'push'
- script: |
        echo Hola Mundo
  displayName: 'Hola Mundo'
